apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-ds
spec:
  selector:
    matchLabel:
      app: httpd
  template:
    metadata:
      name: http-pod
      labels:
        app: httpd
    spec:
      containers:
      - name: http-container
        image: httpd
        ports:
        - containerPort: 80

---

piVersion: v1
kind: Service
metadata: 
  name: maven-clusterip
spec:
  type: ClusterIP
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 80 
        