apiVersion: v1
kind:  ReplicationController
metadata:
  name: java-rc
  namespace: project-2
spec:
  replicas: 5
  selector:
    app: java
  template:
    metadata:
      name: java-pod
      namespace: project-2
      labels:
        app: java
    spec:
      containers:
      - name: java-c 
        image: 8983795200/java-web-app:1 
        ports:
        - containerPort: 8080
          


---

apiVersion: v1
kind: Service
metadata: 
  name: java-np-svc
  namespace: project-2
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 8080
    nodePort: 30032


        
    