apiVersion: apps/v1
kind:  ReplicaSet
metadata:
  name: java-rs
  namespace: project-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      name: java-pod
      namespace: project-2
      labels:
        app: java
    spec:
      containers:
      - name: java-c 
        image: 8983795200/java-web-app:1 
        ports:
        - containerPort: 8080
          


---

apiVersion: v1
kind: Service
metadata: 
  name: java-np-svc-rs
  namespace: project-2
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 8080
    nodePort: 30032