apiVersion: v1
kind: Pod
metadata:
  name: maven-pod
  namespace: project-2
spec:
  containers:
  - name: maven-container
    image: 8983795200/maven-web-application:12
    ports:
    - containerPort: 8080