apiVersion: v1
kind: Service
metadata: 
  name: maven-lb-svc
  namespace: project-2
spec:
  type: LoadBalancer
  selector:
    app: maven-app
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 8080     #containerport