apiVersion: v1
kind: Service
metadata: 
  name: maven-node-port
  namespace: project-2
spec:
  type: NodePort
  selector:
    app: maven-app
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 8080
    nodePort: 30032