apiVersion: v1
kind: Namespace
metadata:
  name: project-2

---
#Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota
  namespace: project-2
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: 1	
---