apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-recreate
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 120
  replicas: 4
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      name: java-pod
      labels:
        app: js
    spec:
      containers:
      - name: java-container
        image: 8983795200/java-web-app:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: rollig-np-svc
spec:
  type: NodePort
  selector:
    app: js
  ports:
  - protocol: TCP
    port: 80            #<serviceport>
    targetPort: 8080
    nodePort: 30330
